forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-stdlib', '4.17.0'
mod 'puppetlabs-apt', '4.1.0'
mod 'puppetlabs-inifile', '1.6.0'
mod 'danieldreier-autosign', '0.2.0'
mod 'puppet-puppetserver', '3.0.0'
